export const welcomePhrases = [
    { ar: "تدريب عملي لسرعة ودقة الكتابة مع مسار تقدم واضح.", en: "Practical typing-speed and accuracy training with a clear progression path." },
    { ar: "تطوير مستمر لسرعة كتابتك وتتبع دقيق لمستواك.", en: "Continuous improvement for your typing speed and accurate tracking of your progress." },
    { ar: "عزز دقتك وضاعف سرعتك من خلال تدريبات مخصصة.", en: "Enhance your accuracy and double your speed through customized exercises." },
    { ar: "مسار تدريبي يركز على الكتابة السريعة والدقيقة.", en: "A training path focused on fast and accurate typing." },
    { ar: "تحدى نفسك وارفع سرعة طباعتك في مسار تصاعدي.", en: "Challenge yourself and increase your typing speed on an upward path." },
    { ar: "دقة أعلى وسرعة أكبر، مع إحصائيات تقيس كل تطور.", en: "Higher accuracy and greater speed, with statistics to measure every improvement." },
    { ar: "ارتقِ بمستوى طباعتك عبر تدريب عملي ومسار واضح.", en: "Elevate your typing level through practical training and a clear path." },
    { ar: "منصة عملية لتعزيز دقة وسرعة الكتابة بأسلوب تدريجي.", en: "A practical platform to gradually enhance typing accuracy and speed." },
    { ar: "ارسم مسار نجاحك في الكتابة مع تدريبات مخصصة للسرعة.", en: "Chart your path to typing success with speed-focused exercises." },
    { ar: "تخلص من الأخطاء الإملائية وضاعف سرعتك بخطوات ملموسة.", en: "Eliminate typos and double your speed with tangible steps." },
    { ar: "بين السرعة والدقة مسار تدريبي يأخذك للاحتراف.", en: "Between speed and accuracy, a training path takes you to professionalism." },
    { ar: "أتقن مهارة الكتابة عبر تتبع مستوى تقدمك بدقة.", en: "Master the skill of typing by accurately tracking your progress level." },
    { ar: "أرقامك تتحدث: سرعة ودقة أكبر في كل جولة تدريب.", en: "Your numbers speak: greater speed and accuracy in every training round." },
    { ar: "تدريب مكثف يجمع بين السرعة البديهية والتطور الواضح.", en: "Intensive training that combines intuitive speed with clear development." },
    { ar: "خطواتك نحو الكتابة السريعة تبدأ هنا، بتتبع مستمر.", en: "Your steps toward fast typing start here, with continuous tracking." },
    { ar: "أنجز نصوصك في ثوانٍ مع منصة التدريب العملية.", en: "Finish your texts in seconds with this practical training platform." },
    { ar: "اختبر قدراتك، واصل التدريب، وكن أسرع في لغتين.", en: "Test your abilities, keep training, and become faster in two languages." },
    { ar: "تحديات يومية تجعل سرعتك في الكتابة عادة طبيعية.", en: "Daily challenges that make your typing speed a natural habit." },
    { ar: "ركز على الشاشة، وتجاوز أرقامك القياسية في كل مرة.", en: "Keep your eyes on the screen and beat your personal records every time." },
    { ar: "لا مجال للخطأ، تدرب لتكون دقيقاً وسريعاً بلا حدود.", en: "No room for errors; train to be infinitely accurate and fast." },
    { ar: "دقة متناهية، سرعة استثنائية، وتقدم ملحوظ جداً.", en: "Ultimate accuracy, exceptional speed, and highly noticeable progress." },
    { ar: "استمر في صقل سرعتك حتى تصبح الكتابة بديهية.", en: "Keep honing your speed until typing becomes second nature." },
    { ar: "كل جولة هنا تجعلك بخطوة أقرب للقب الأسرع.", en: "Every round here gets you one step closer to being the fastest." },
    { ar: "وفر وقتك وضاعف إنتاجيتك بالتدريب العملي المستمر.", en: "Save time and double your productivity with continuous practical training." },
    { ar: "اكتب بلا تردد؛ السرعة والدقة هما المفتاح للتعلم.", en: "Type without hesitation; speed and accuracy are the keys to learning." },
    { ar: "صمم إيقاعك الخاص في الطباعة ليتخطى حدود الدقة.", en: "Design your typing rhythm to surpass the limits of accuracy." },
    { ar: "استثمر في مهارتك ولاحظ التقدم المطرد يومياً.", en: "Invest in your skill and notice steady daily progress." },
    { ar: "منصتك المباشرة نحو كتابة سريعة وخالية من الأخطاء.", en: "Your direct platform towards fast, error-free typing." },
    { ar: "تتبع سرعة أصابعك وهي تطير على لوحة المفاتيح.", en: "Track the speed of your fingers as they fly across the keyboard." },
    { ar: "اكتشف مستوى احترافيتك وتطوره في طباعة الكلمات.", en: "Discover your level of professionalism and its evolution in typing words." },
    { ar: "تجاوز توقعاتك، واكتب كالمحترفين بمسار تدريبي عملي.", en: "Exceed your expectations and type like a pro with a practical training path." },
    { ar: "تجربة تفاعلية مكرسة لتسريع كتابتك بأعلى جودة.", en: "An interactive experience dedicated to speeding up your typing with top quality." },
    { ar: "أتقن لغة الأصابع، اختصر العناء، وعزز سرعتك بشدة.", en: "Master finger placement, save effort, and significantly boost your speed." },
    { ar: "تتبع سجل دائم لأدائك وحفز تطورك طباعيا باستمرار.", en: "Track a permanent record of your performance and constantly motivate your typing progress." },
    { ar: "الوسيلة المثبتة لاختبار سرعتك وبناء أرقام جديدة.", en: "The proven method to test your speed and set new records." },
    { ar: "المسار الأسرع لإجادة الكتابة باللغتين العربية والإنجليزية.", en: "The fastest path to mastering typing in both Arabic and English." },
    { ar: "تدريب مباشر يصقل سرعتك ويمحو أخطاء الطباعة الشائعة.", en: "Direct training that polishes your speed and erases common typing mistakes." },
    { ar: "ابنِ ذاكرتك العضلية بخطوات تدريبية ممنهجة وبسيطة.", en: "Build your muscle memory with systematic and simple training steps." },
    { ar: "تحكم في إيقاعك وطور سرعتك مع كل كلمة جديدة.", en: "Control your rhythm and develop your speed with every new word." },
    { ar: "سجل أرقاماً لا يمكن كسرها، ومارس الكتابة بحرية.", en: "Set unbreakable records and practice typing freely." },
    { ar: "نحن نقيس التطور، وأنت تصنع السرعة المطلقة والممتعة.", en: "We measure the progress, and you dictate the ultimate enjoyable speed." },
    { ar: "حول الطباعة من مجهود إلى مهارة بديهية وسريعة.", en: "Turn typing from an effort into an intuitive and fast skill." },
    { ar: "تدرج في المستويات وكن الأول في سرعة الكتابة.", en: "Ascend the levels and be the first in typing speed." },
    { ar: "التجربة المخصصة لرفع الدقة وتقليل زمن الاستجابة.", en: "The tailored experience for increasing accuracy and reducing response time." },
    { ar: "أثبت جدارتك وحقق معدلات سرعة لم تصلها من قبل.", en: "Prove your worth and achieve speed rates you've never reached before." },
    { ar: "راقب انخفاض نسبة أخطائك وزيادة معدل كلماتك.", en: "Watch your error rate drop and your word count rise." },
    { ar: "منصة مخصصة لرفع الكفاءة الطباعية للمستوى المطلوب.", en: "A dedicated platform to raise typing efficiency to the desired level." },
    { ar: "اكتب بكل ثقة وحافظ على وتيرتك السريعة بثبات عال.", en: "Type with confidence and maintain your fast pace with high stability." },
    { ar: "تدريب يومي ممتع لضمان الدقة وتوفير وقت المهام.", en: "Fun daily training to ensure accuracy and save time on tasks." },
    { ar: "اكتب بدون النظر، وسارع في مسار تدريبك الهادف.", en: "Type without looking, and accelerate through your purposeful training path." },
    { ar: "درب سرعتك الآن، قبل أن يطبع الذكاء الاصطناعي كلماتك بدلاً منك.", en: "Train your typing speed now, before AI types your words for you." },
    { ar: "الذكاء الاصطناعي يقرأ أفكارك، لكنه لن يكتبها بسرعة إلا إذا تدربت أنت.", en: "AI might read your mind, but it won't type fast until you train." },
    { ar: "لا يوجد ذكاء اصطناعي يعلم كيفية كتابة هذا الوصف؛ نحن نعتمد على سرعتك فقط.", en: "There is no AI to write this description; we just rely on your typing speed." },
    { ar: "سرعتك في الكتابة هي الميزة البشرية التي لم يتمكن الذكاء الاصطناعي من سرقتها بعد.", en: "Your typing speed is the one human trait AI hasn't managed to steal yet." },
    { ar: "هل تخشى سيطرة الذكاء الاصطناعي؟ تغلب عليه بالطباعة السريعة ولن يلحق بك.", en: "Afraid of an AI takeover? Beat it with fast typing." }
];
